/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_peter_source_dydex_jni_DyLoadDex */

#ifndef _Included_com_peter_source_dydex_jni_DyLoadDex
#define _Included_com_peter_source_dydex_jni_DyLoadDex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_peter_source_dydex_jni_DyLoadDex
 * Method:    loadDexArray
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_peter_source_dydex_jni_DyLoadDex_loadDexArray
  (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
